apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-pipeline-alerting
  labels:
    tenant: rhtap
spec:
  groups:
    - name: pipeline_alerts
      interval: 1m
      rules:
        - alert: HighSchedulingOverhead
          expr: |
            1-(sum by (source_cluster) (increase(pipeline_service_schedule_overhead_percentage_sum{status='succeded'}[30m]))
            /
            sum by (source_cluster) (increase(pipeline_service_schedule_overhead_percentage_count{status='succeded'}[30m])))
            < 0.95
          for: 12h
          labels:
            severity: normal
            slo: "false"
          annotations:
            summary: >-
              Tekton has a scheduling overhead vs. PipelineRun durations of <95%
            description: >-
              Tekton controller on cluster {{ $labels.source_cluster }} factoring out the time needed to receive PipelineRun creation
              events from the overall PipelineRun execution time is at {{ $value | humanizePercentage }} instead of 95% or greater.
            alert_team_handle: <!subteam^S04PYECHCCU>
            team: pipelines
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/pipeline-service/slos/scheduling-overhead.md
        - alert: HighExecutionOverhead
          expr: |
            1-(sum by (source_cluster) (increase(pipeline_service_execution_overhead_percentage_sum{status='succeded'}[30m]))
            /
            sum by (source_cluster) (increase(pipeline_service_execution_overhead_percentage_count{status='succeded'}[30m])))
            < 0.95
          for: 12h
          labels:
            severity: normal
            slo: "false"
          annotations:
            summary: >-
              Tekton has a execution overhead vs. PipelineRun durations of <95%
            description: >-
              Tekton controller on cluster {{ $labels.source_cluster }} factoring out the time needed to create
              underlying TaskRuns from the overall PipelineRun execution time is at {{ $value | humanizePercentage }} instead of 95% or greater.
            alert_team_handle: <!subteam^S04PYECHCCU>
            team: pipelines
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/pipeline-service/slos/execution-overhead.md
        - alert: CorePipelineControllerRepeatedRestarts
          expr: |
            sum by (source_cluster) (increase(kube_pod_container_status_restarts_total{namespace="openshift-pipelines", pod=~"tekton-.*|pipelines-as-code-.*"}[5m])) > 0
          for: 5m
          labels:
            severity: critical
            slo: "true"
          annotations:
            summary: >-
              Tekton controller is rapidly restarting.
            description: >-
              Tekton controllers on cluster {{ $labels.source_cluster }} have restarted {{ $value }} times recently.
            alert_team_handle: <!subteam^S04PYECHCCU>
            team: pipelines
            # link will be available once https://gitlab.cee.redhat.com/konflux/docs/sop/-/merge_requests/163 merges
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/pipeline-service/slos/core-pipeline-controller-repeated-restarts.md
        - alert: PipelineControllerDeadlock
          expr: |
            sum by (source_cluster) (increase(pipelinerun_kickoff_not_attempted_count[2m])) > 0
          for: 75m
          labels:
            severity: critical
            slo: "true"
          annotations:
            summary: >-
              Tekton pipeline controller appears to have stopped processing active pipelineruns which have not been started yet.
            description: >-
              Tekton pipeline controller on cluster {{ $labels.source_cluster }} has appeared deadlocked on {{ $value }} pipelineruns.
            alert_team_handle: <!subteam^S04PYECHCCU>
            team: pipelines
            # link will be available once https://gitlab.cee.redhat.com/konflux/docs/sop/-/merge_requests/163 merges
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/pipeline-service/slos/tekton-pipeline-related-deadlocks.md
        - alert: TaskControllerDeadlock
          expr: |
            sum by (source_cluster) (increase(taskrun_pod_create_not_attempted_or_pending_count[2m])) - sum by (source_cluster) (increase(tekton_pipelines_controller_running_taskruns_throttled_by_quota[2m])) - sum by (source_cluster) (increase(tekton_pipelines_controller_running_taskruns_throttled_by_node[2m]))> 0
          for: 75m
          labels:
            severity: critical
            slo: "true"
          annotations:
            summary: >-
              Tekton taskrun controller appears to have stopped processing active taskruns whose underlying Pod have not failed Kubernetes screening.
            description: >-
              Tekton taskrun controller on cluster {{ $labels.source_cluster }} has appeared deadlocked on {{ $value }} taskruns.
            alert_team_handle: <!subteam^S04PYECHCCU>
            team: pipelines
            # link will be available once https://gitlab.cee.redhat.com/konflux/docs/sop/-/merge_requests/163 merges
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/pipeline-service/slos/tekton-pipeline-related-deadlocks.md
        - alert: ResolverControllerDeadlock
          expr: |
            sum by (source_cluster) (increase(pending_resolutionrequest_count[2m])) > 0
          for: 75m
          labels:
            severity: critical
            slo: "true"
          annotations:
            summary: >-
              Tekton resolver controller appears to have stopped processing active resolutionrequests which have not been started yet.
            description: >-
              Tekton resolver controller on cluster {{ $labels.source_cluster }} has appeared deadlocked on {{ $value }} resolutionrequests.
            alert_team_handle: <!subteam^S04PYECHCCU>
            team: pipelines
            # link will be available once https://gitlab.cee.redhat.com/konflux/docs/sop/-/merge_requests/163 merges
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/pipeline-service/slos/tekton-pipeline-related-deadlocks.md
        - alert: ChainsControllerDeadlock
          expr: |
            sum by (source_cluster) (increase(watcher_workqueue_depth{container='tekton-chains-controller',app='tekton-chains-controller'}[2m])) > 50
          for: 75m
          labels:
            severity: critical
            slo: "true"
          annotations:
            summary: >-
              Tekton chains controller appears to have stopped processing active pipelineruns.
            description: >-
              Tekton chains controller on cluster {{ $labels.source_cluster }} has appeared deadlocked on {{ $value }} pipelinerun events.
            alert_team_handle: <!subteam^S04PYECHCCU>
            team: pipelines
            # link will be available once https://gitlab.cee.redhat.com/konflux/docs/sop/-/merge_requests/163 merges
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/pipeline-service/slos/tekton-pipeline-related-deadlocks.md
        - alert: ChainsControllerPerformance
          expr: |
            (sum by (source_cluster) (increase(watcher_client_latency_bucket{app='tekton-chains-controller',le='10'}[5m]))
            /
            sum by (source_cluster) (increase(watcher_client_latency_bucket{app='tekton-chains-controller',le='+Inf'}[5m])))
            < 0.50
          for: 75m
          labels:
            severity: normal
            slo: "false"
          annotations:
            summary: >-
              Tekton chains controller performance appears degraded with uncommonly high client latency.
            description: >-
              Tekton chains controller on cluster {{ $labels.source_cluster }} performance appears degraded with client latency {{ $value | humanizePercentage }}.
            alert_team_handle: <!subteam^S04PYECHCCU>
            team: pipelines
            # link will be available once https://issues.redhat.com/browse/SRVKP-5899 is complete
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/pipeline-service/slos/chains-performance.md
        - alert: ResultsDeadlock
          expr: |
            sum by (source_cluster) (increase(tekton_pipelines_controller_pipelinerun_count[5m])) > 0
            and
            sum by (source_cluster) (increase(grpc_server_handled_total{job='tekton-results-api', grpc_service=~'tekton.results.*'}[5m])) == 0
          for: 75m
          labels:
            severity: critical
            slo: "true"
          annotations:
            summary: >-
              Tekton results appears to have stopped processing active pipelineruns.
            description: >-
              Tekton results on cluster {{ $labels.source_cluster }} appears deadlocked on pipelinerun events.
            alert_team_handle: <!subteam^S04PYECHCCU>
            team: pipelines
            # link will be available once https://gitlab.cee.redhat.com/konflux/docs/sop/-/merge_requests/163 merges
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/pipeline-service/slos/tekton-pipeline-related-deadlocks.md
        - alert: ResultsSuccessRateTooManyErrors
          expr: |
            sum by (source_cluster) (increase(grpc_server_handled_total{job='tekton-results-api', grpc_service=~'tekton.results.*', grpc_code='OK'}[10m]))
            /
            sum by (source_cluster) (increase(grpc_server_handled_total{job='tekton-results-api', grpc_service=~'tekton.results.*'}[10m]))
            < 0.75
            and
            sum by (source_cluster) (increase(grpc_server_handled_total{job='tekton-results-api', grpc_service=~'tekton.results.*'}[10m])) > 0
          for: 75m
          labels:
            severity: critical
            slo: "true"
          annotations:
            summary: >-
              Tekton results is experiencing too many API errors.
            description: >-
              Tekton results on cluster {{ $labels.source_cluster }} only has an API success rate of {{ $value | humanizePercentage }}.
            alert_team_handle: <!subteam^S04PYECHCCU>
            team: pipelines
            # link will be available once https://issues.redhat.com/browse/SRVKP-5900 is done
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/pipeline-service/slos/tekton-result-high-errors.md
        - alert: PACControllerDeadlock
          expr: |
            sum by (source_cluster) (increase(pac_watcher_work_queue_depth[2m])) > 50
          for: 75m
          labels:
            severity: critical
            slo: "true"
          annotations:
            summary: >-
              Tekton PAC controller appears to have stopped processing active pipelineruns.
            description: >-
              Tekton PAC controller on cluster {{ $labels.source_cluster }} has appeared deadlocked on {{ $value }} pipelinerun events.
            alert_team_handle: <!subteam^S04PYECHCCU>
            team: pipelines
            # link will be available once https://gitlab.cee.redhat.com/konflux/docs/sop/-/merge_requests/163 merges
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/pipeline-service/slos/tekton-pipeline-related-deadlocks.md
        - alert: PACControllerPerformance
          expr: |
            (sum by (source_cluster) (increase(pac_watcher_client_latency_bucket{le='10'}[5m]))
            /
            sum by (source_cluster) (increase(pac_watcher_client_latency_bucket{le='+Inf'}[5m])))
            < 0.50
          for: 75m
          labels:
            severity: normal
            slo: "false"
          annotations:
            summary: >-
              Tekton PAC controller performance appears degraded with uncommonly high client latency.
            description: >-
              Tekton PAC controller on cluster {{ $labels.source_cluster }} performance appears degraded with client latency {{ $value | humanizePercentage }}.
            alert_team_handle: <!subteam^S04PYECHCCU>
            team: pipelines
            # link will be available once https://issues.redhat.com/browse/SRVKP-5899 is complete
            runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/pipeline-service/slos/pac-performance.md
